resolver: lts-11.17

packages:
- snowdrop-block
- snowdrop-block-exec
- snowdrop-core
- snowdrop-dba
- snowdrop-dba-avlp
- snowdrop-dba-simple
- snowdrop-hetero
- snowdrop-mempool
- snowdrop-util

extra-deps:
- tasty-hedgehog-0.2.0.0
- pretty-tree-0.1.0.0
- time-units-1.0.0
- componentm-0.0.0.2
  #- serokell-util-0.8.0
- teardown-0.5.0.0
- universum-1.1.1

- git: https://github.com/serokell/auth-data-structures.git
  commit: c46d81fac79bbc1e4efcc6c4568a1500b273bd60

- co-log-core-0.1.1

- vinyl-0.9.3
- union-0.1.2

# for universum (greater versions conflict)
- formatting-6.2.5

ghc-options:
    snowdrop-util:       -Werror
    snowdrop-core:       -Werror
    snowdrop-block:      -Werror
    snowdrop-block-exec: -Werror
    snowdrop-hetero:     -Werror
    snowdrop-dba:        -Werror
    snowdrop-dba-avlp:   -Werror
    snowdrop-dba-simple: -Werror
    snowdrop-mempool:    -Werror
